Use MySQL release keys that are still valid
The old release keys have expired. These new release keys are used for signing releases from 8.0.36, and so the version of MySQL 8 has been updated to this version.

I haven't been able to test that this works because the base image for the Dockerfile requires auth:

```
ERROR: failed to solve: marketplace.gcr.io/google/c2d-debian11: pulling from host marketplace.gcr.io failed with status code [manifests latest]: 401 Unauthorized
```

This fixes #98 which is blocking CI and presubmits for google/trillian and google/certificate-transparency-go.